# Generated by Django 4.2.5 on 2023-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', max_length=6, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PAID', 'Оплачивается'), ('ORDER_PROCCESING', 'Обработка заказа'), ('SUCCESFULLY', 'Успешно ожидайте заказ в течение недели'), ('WAITING', 'Ваш заказ прибудет через 4 дня'), ('ARRIVED', 'Ваш заказ прибыл!')], default='PAID', max_length=22, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
