# Generated by Django 4.2.5 on 2023-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_options_order_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='signer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='', max_length=6, unique=True, verbose_name='ID заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDER_PROCCESING', 'Обработка заказа'), ('SUCCESFULLY', 'Успешно ожидайте заказ в течение недели'), ('WAITING', 'Ваш заказ прибудет через 4 дня'), ('ARRIVED', 'Ваш заказ прибыл!')], default='ORDER_PROCCESING', max_length=16, verbose_name='Статус заказа'),
        ),
    ]
