# Generated by Django 4.2.5 on 2023-09-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_email_order_signer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDER_PROCESSING', 'Обработка заказа'), ('SUCCESSFULLY', 'Успешно ожидайте заказ в течение недели'), ('ARRIVED', 'Ваш заказ прибыл!'), ('RECEIVED', 'Получен')], default='ORDER_PROCESSING', max_length=16, verbose_name='Статус заказа'),
        ),
    ]
