version: '3.8'


services:
  redis:
    image: redis:7.0.11-alpine
  api:
    container_name: melorn
    build:
      context: ./melorn
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - melorn:/usr/src/app
      - static_volume:/home/app/api/static
      - media_volume:/home/app/api/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - db
  celery:
    container_name: celery
    build:
      context: ./melorn
      dockerfile: Dockerfile.prod
    command: celery -A config worker --loglevel=info
    volumes:
      - melorn:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
    - static_volume:/home/app/api/static
    - media_volume:/home/app/api/media
    - www-http:/var/www/certbot/
    - ect-letsencrypt:/etc/nginx/ssl/
    depends_on:
      - api
  certbot:
    image: certbot/certbot:latest
    volumes:
      - www-http:/var/www/html/
      - ect-letsencrypt:/etc/letsencrypt/
    command: certonly --webroot --webroot-path=/var/www/html --email adilmarsov5@gmail.com --agree-tos --no-eff-email -d collecta.club
    depends_on:
      - nginx



volumes:
  postgres_data:
  melorn:
  static_volume:
  media_volume:
  ect-letsencrypt:
  www-http: